services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: aquarela
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    image: desafio_aquarela
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app 
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/aquarela
      ALGORITHM: 'HS256'
      SECRET_KEY: 'supersecretkey'
    command: bash -c "poetry run alembic upgrade head && poetry run uvicorn --host 0.0.0.0 desafio_aquarela.app:app --reload"

volumes:
  pgdata: