"""Adding enum to status

Revision ID: 2a0d14f6c638
Revises: 
Create Date: 2024-12-15 16:41:34.760870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a0d14f6c638'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaders',
    sa.Column('registrationCode', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('registrationCode')
    )
    op.create_table('position',
    sa.Column('registrationCode', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('registrationCode')
    )
    op.create_table('users',
    sa.Column('registrationCode', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lastName', sa.String(), nullable=False),
    sa.Column('positionCode', sa.Integer(), nullable=False),
    sa.Column('leaderCode', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'VACATION', name='status_enum', create_constraint=True), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('wage', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['leaderCode'], ['leaders.registrationCode'], ),
    sa.ForeignKeyConstraint(['positionCode'], ['position.registrationCode'], ),
    sa.PrimaryKeyConstraint('registrationCode')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('position')
    op.drop_table('leaders')
    # ### end Alembic commands ###
