"""Creating position table

Revision ID: 8a1f76a9caa0
Revises: 9928fcc91097
Create Date: 2024-12-15 13:36:49.325893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a1f76a9caa0'
down_revision: Union[str, None] = '9928fcc91097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('registrationCode', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('registrationCode')
    )
    op.create_foreign_key(None, 'users', 'position', ['positionCode'], ['registrationCode'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_table('position')
    # ### end Alembic commands ###
